<?php


namespace Controller;

use Controller\TodoController;
use Core\Config;

class UserTodoController  extends TodoController

{
    public function actionShow(array $data)
    {


        parent::actionShow($data); // TODO: Change the autogenerated stub
        $this->view
            ->setFolder("usertodo")
            ->addData(
                [
                    "user_id" => $_SESSION['user']['id'],
                    "usersList" => $this->usersTable->getUsers(),
                    'table' => $this
                        ->table
                        ->reset()
                        ->setPageSize(Config::PAGE_SIZE)
                        ->getTodoPageUserFilter($data['get']['page'] ?? 1, $_SESSION['user']['id'])
                ]
            );
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data); // TODO: Change the autogenerated stub
        $this
            ->view
            ->setFolder('usertodo');

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
            ]
        );
    }
}
